name: TG Stats Collection

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Setup environment
        run: |
          {
            echo "TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}"
            echo "TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}"
            echo "TELEGRAM_CHANNELS='${{ secrets.TELEGRAM_CHANNELS }}'"
            echo "GOOGLE_SHEET_URL=${{ secrets.GOOGLE_SHEET_URL }}"
            echo "TIMEZONE=Europe/Moscow"
            echo "MODE=regular"
            echo "GOOGLE_CREDENTIALS_PATH=google_credentials.json"
          } > .env
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > google_credentials.json
          
      - name: Run collection
        run: python -m src.main