name: TG Stats Collection

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Write Google Credentials
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > google_credentials.json
                  
      - name: Run collection
        env:
          TELEGRAM_CHANNELS: ${{ secrets.TELEGRAM_CHANNELS }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TG_SESSION: ${{ secrets.TG_SESSION }}
          GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
          GOOGLE_CREDENTIALS_PATH: "google_credentials.json"
          TIMEZONE: "Europe/Moscow"
          MODE: "regular"
        run: python -m src.main